import { jsPDF } from 'jspdf';
import type { Edge } from '@xyflow/react';
import type { RFNode } from '@/types/topology';

export function buildCiscoConfigText(nodes: RFNode[], edges: Edge[]): string {
  const lines: string[] = [
    '! Generated by Maptive Elite — topology export',
    'service timestamps debug datetime msec',
    'service timestamps log datetime msec',
    '',
  ];
  for (const n of nodes) {
    const host = n.id.replace(/[^a-zA-Z0-9_-]/g, '_');
    lines.push(`hostname ${host}`);
    lines.push(`! ${n.data.deviceType} — ${n.data.label}`);
    lines.push('!');
  }
  lines.push('! --- Logical links (descriptions) ---');
  let i = 0;
  for (const e of edges) {
    i += 1;
    const label = typeof e.label === 'string' ? e.label : 'link';
    lines.push(
      `interface VirtualEthernet${i}`,
      ` description To ${e.target} from ${e.source} (${label})`,
      ' no shutdown',
      '!'
    );
  }
  lines.push('end', 'write memory');
  return lines.join('\n');
}

export function downloadTextFile(filename: string, content: string) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportTopologyPdf(title: string, nodes: RFNode[], edges: Edge[]) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 48;
  let y = margin;
  doc.setFontSize(16);
  doc.text(title, margin, y);
  y += 28;
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`Nodes: ${nodes.length} · Edges: ${edges.length}`, margin, y);
  y += 22;
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.text('Devices', margin, y);
  y += 16;
  doc.setFontSize(9);
  for (const n of nodes) {
    if (y > 760) {
      doc.addPage();
      y = margin;
    }
    doc.text(
      `• ${n.id}  (${n.data.deviceType})  ${n.data.label}`,
      margin,
      y
    );
    y += 14;
  }
  y += 10;
  doc.setFontSize(11);
  doc.text('Links', margin, y);
  y += 16;
  doc.setFontSize(9);
  for (const e of edges) {
    if (y > 760) {
      doc.addPage();
      y = margin;
    }
    const lab = typeof e.label === 'string' ? e.label : '';
    doc.text(`${e.source} → ${e.target}  ${lab}`, margin, y);
    y += 14;
  }
  doc.save('maptive-topology-report.pdf');
}
export { buildCiscoConfigText as exportCiscoConfig, exportTopologyPdf as exportToPdf };
